version: '3'
networks:
  kafka_network:
    external: true
    driver: bridge

services:
  controller2:
    image: confluentinc/cp-kafka:latest
    container_name: controller2
    ports:
      - "9222:9222"
    environment:
      KAFKA_NODE_ID: 22
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '11@controller1:9111,22@controller2:9222,33@controller3:9333'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9222'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-controller-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - "./controller2_data:/tmp/kraft-controller-logs"
    networks:
      - kafka_network
