version: '3'
networks:
  kafka_network:
    external: true
    driver: bridge

services:
  sink-connect2:
    image: confluentinc/cp-kafka-connect:latest
    container_name: sink-connect2
    ports:
      - "28083:28083"
    environment:
      CONNECT_LISTENERS: 'http://0.0.0.0:28083'
      CONNECT_BOOTSTRAP_SERVERS: 'broker1:19091,broker2:29092,broker3:39093'
      CONNECT_REST_PORT: 28083
      CONNECT_GROUP_ID: "connect-sink-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-sink-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-sink-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-sink-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "sink-connect2"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/opt/kafka/plugins"
    volumes:
      - ./sink_connect_data:/var/lib/kafka/data
      - ./sink_connect_logs:/var/log/kafka
      - ./sink_connect_plugins:/opt/kafka/plugins
    networks:
      - kafka_network
    command:
      - bash
      - -c
      - |
        echo "Installing Connectors"
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
        confluent-hub install --no-prompt microsoft/mssql-jdbc:latest
        #
        echo "Downloading MSSQL JDBC driver"
        mkdir -p /opt/kafka/plugins/mssql-jdbc
        curl -L https://github.com/microsoft/mssql-jdbc/releases/download/v9.4.0/mssql-jdbc-9.4.0.jre8.jar -o /opt/kafka/plugins/mssql-jdbc/mssql-jdbc-9.4.0.jre8.jar
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        #
        sleep infinity
