version: '3'
networks:
  kafka_network:
    external: true
    driver: bridge

services:
  source-connect1:
    image: confluentinc/cp-kafka-connect:latest
    container_name: source-connect1
    ports:
      - "8083:8083"
    environment:
      CONNECT_LISTENERS: 'http://0.0.0.0:8083'
      CONNECT_BOOTSTRAP_SERVERS: 'broker1:19091,broker2:29092,broker3:39093'
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-source-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-source-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-source-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-source-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "source-connect1"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/opt/kafka/plugins"
    volumes:
      - ./source_connect_data:/var/lib/kafka/data
      - ./source_connect_logs:/var/log/kafka
      - ./source_connect_plugins:/opt/kafka/plugins
    networks:
      - kafka_network
    command:
      - bash
      - -c
      - |
        echo "Installing Connector"
        confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:2.5.4
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        #
        sleep infinity
