version: "3.8"

networks:
  kafka_network:
    external: true
    driver: bridge

services:
  sql-server-db:
    restart: "no"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "admin123$%"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_COLLATION: "LATIN1_GENERAL_100_CI_AS_SC_UTF8"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./mssql_data:/var/opt/mssql
    networks:
      - kafka_network
